# Generated by Django 3.2 on 2022-05-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220514_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pricess', to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.product', verbose_name='Product'),
        ),
    ]
