# Generated by Django 3.2 on 2022-05-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='product',
        ),
    ]
